### ISSUE TITLE
Add configurable admin accounts

### ISSUE THREAD

**Issue by Torxed** [Torxed/coreborn-api#5]
Currently, `127.0.0.1` is "admin".
It would be better if we could in the config: https://github.com/Torxed/coreborn-api/blob/ecaea3578088566154b6d83e6d366edab3c50398/coreborn.toml.example#L1-L4

Add a:
```toml
[accounts.<steam-id>]
groups = ["admin"]
```

Depending on: https://github.com/Torxed/coreborn-api/issues/3
